# -*- coding: utf-8 -*-
"""Optical Character Recognition.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fDxiIlM_4EsvZUOWrWFC50ogVN_-oyhe
"""

!sudo apt install tesseract-ocr
!pip install pytesseract

import pytesseract
import cv2 
from google.colab.patches import cv2_imshow
import shutil
import os
import random
try:
 from PIL import Image
except ImportError:
 import Image

"""Below block of code doesn't need to be run for the algorithm to work"""

#testing for the output 
image = cv2.cvtColor(cv2.imread(r'/content/drive/MyDrive/Colab Notebooks/testImages/ParallaxParagraph.JPG'), cv2.COLOR_BGR2GRAY )
cv2_imshow(image)

"""Below block runs to give the extracted text from the image.
Make sure to either upload and image or mount drive and specify the image path for the 'image' variable
"""

#img_cv = cv2.imread(r'/content/drive/MyDrive/Colab Notebooks/labelMe.png')
# By default OpenCV stores images in BGR format and since pytesseract assumes RGB format,
# we need to convert from BGR to RGB format/mode:
image = cv2.cvtColor(cv2.imread(r'/content/drive/MyDrive/Colab Notebooks/testImages/ParallaxParagraph.JPG'), cv2.COLOR_BGR2GRAY )
img_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
print(pytesseract.image_to_string(img_rgb))